### PR TITLE
deps: Add webpack 4 compatibility

### LINKED ISSUE #32: Support Webpack v4
I'm getting the following error:

```bash
ERROR in ./src/utils/404/404.extract.html
Module build failed: TypeError: Cannot read property 'output' of undefined
    at Object.extractLoader (./node_modules/extract-loader/src/extractLoader.js:31:72)
 @ ./src/utils/404/404.component.ts 18:15-44
 @ ./src/app/index.routing.ts
 @ ./src/app/index.module.ts
 @ ./src/main.ts
```

This points to the line https://github.com/peerigon/extract-loader/blob/master/src/extractLoader.js#L31, which seems `this.options.output` is no longer defined.

According to the v4 migration guide ([here](https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202)), `this.options` has been removed.  Instead of loader-utils and checking `this.options`, you now get all options from `this.query`.  Although, I'm not sure if that carries the `publicPath` option set by the webpack config.  Also not sure what that `publicPath`'s intended usage is here within the context of extract-loader.  Setting it to `null` worked for me.

### PR DESCRIPTION
**Pull request by benurb**
Should fix #32 
Also should not break compatibility with previous webpack versions.

### CODE REVIEW

**Comment by benurb** [comment]
Test fails because webpack 4 is not compatible with Node.js 4. We can change the .travis.yml here, too, but I also created a PR for this #34

File: src/extractLoader.js [hunk 1]
```diff
@@ -28,7 +28,9 @@ const rndPlaceholder = "__EXTRACT_LOADER_PLACEHOLDER__" + rndNumber() + rndNumbe
 function extractLoader(content) {
     const callback = this.async();
     const options = getOptions(this) || {};
-    const publicPath = options.publicPath === undefined ? this.options.output.publicPath : options.publicPath;
+    const publicPath = options.publicPath ||
+        (this.options && this.options.output && this.options.output.publicPath) ||
+        (this._compilation && this._compilation.outputOptions && this._compilation.outputOptions.publicPath);
```
Comment (jhnns) [inline src/extractLoader.js]: 1. I think we should check for `"publicPath" in options` here because an empty string as `publicPath` is a valid option
2. The check for `this.options` is necessary with webpack 4, but could you add a `TODO` that this should be removed with the next major release
3. I guess you've added the `this._compilation` part so that we can still derive the `publicPath`. We should also remove that with the next major release since [`this._compilation` is likely to be removed in the future](https://webpack.js.org/api/loaders/#deprecated-context-properties).

File: test/extractLoader.test.js [hunk 2]
```diff
@@ -92,8 +92,13 @@ describe("extractLoader", () => {
...
             const basePath = path.dirname(__dirname); // returns the parent dirname
-            const dependencies = stats.compilation.fileDependencies.map(
-                dependency => dependency.slice(basePath.length)
+            const dependencies = [];
+
+            // Use .forEach instead of map to be compatible with Array (webpack < 4) and SortableSet/Set (webpack 4+)
+            stats.compilation.fileDependencies.forEach(
+                dependency => {
+                    dependencies.push(dependency.slice(basePath.length));
+                }
```
Comment (jhnns) [inline test/extractLoader.test.js]: I think, this could be solved with `Array.from`:

```js
const dependencies = Array.from(stats.compilation.fileDependencies)
    .map(dependency => dependency.slice(basePath.length));
```

What do you think?

File: src/extractLoader.js (hunk 1 above)
Comment (jhnns) [reply src/extractLoader.js]: I've created an issue for that: https://github.com/peerigon/extract-loader/issues/35

Comment (benurb) [reply src/extractLoader.js]: 1. You're right. I'll change that.
2. and 3. #35 is enough, isn't it?

File: test/extractLoader.test.js (hunk 2 above)
Comment (benurb) [reply test/extractLoader.test.js]: Yep, looks good. I'll change that 👍

**Comment by benurb** [comment]
I've addressed your remarks 👍  PTAL

File: src/extractLoader.js [hunk 3]
```diff
@@ -28,9 +28,7 @@ const rndPlaceholder = "__EXTRACT_LOADER_PLACEHOLDER__" + rndNumber() + rndNumbe
 function extractLoader(content) {
     const callback = this.async();
     const options = getOptions(this) || {};
-    const publicPath = options.publicPath ||
-        (this.options && this.options.output && this.options.output.publicPath) ||
-        (this._compilation && this._compilation.outputOptions && this._compilation.outputOptions.publicPath);
+    const publicPath = options.publicPath || getPublicPath(this);
```
Comment (jhnns) [inline src/extractLoader.js]: If `options.publicPath` was an empty string, the empty string should be used. Maybe change that line to:

```js
const publicPath = "publicPath" in options ? options.publicPath : getPublicPath(this)
```

Or maybe put that logic into `getPublicPath` as well?

Comment (benurb) [reply src/extractLoader.js]: The idea behind `getPublicPath()` was a function that can be removed when we work on #35 .
That's why options was not included.
